productly/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.inicio, name="inicio"),
    path('admin/', admin.site.urls),
    path('productos/', include('productos.urls'))
]

productos/urls.py
from django.urls import path
from . import views

# /productos

app_name = 'productos'
urlpatterns = [
    path('',
         views.index,
         name='index'),
    path(
        '<int:producto_id>',
        views.detalle,
        name='detalle'),
    path(
        'formulario',
        views.formulario,
        name='formulario'
    )
]

productos/models.py
from django.db import models
from django.utils import timezone

# Create your models here.


class Categoria(models.Model):
    nombe = models.CharField(max_length=255)

    def __str__(self):
        return self.nombe


class Producto(models.Model):

    nombre = models.CharField(max_length=255)
    stock = models.IntegerField()
    puntaje = models.FloatField()
    # Cascade: Eliminar el producto
    # Protect: Lanza un error
    # Restrict: Solo elimina si no existen productos
    # Set_null: Actualiza un valor nulo
    # Set_default: asigna valor por defecto
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    creado_en = models.DateField(default=timezone.now)

    def __str__(self):
        return self.nombre

productos/forms.py
from . import models
from django.forms import ModelForm


class ProductoForm(ModelForm):
    class Meta:
        model = models.Producto
        fields = ['nombre', 'stock', 'puntaje', 'categoria']

productly/views.py
from django.shortcuts import render


def inicio(request):
    return render(
        request,
        'inicio.html'
    )

productos/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404, HttpResponse, HttpResponseRedirect

from productos.forms import ProductoForm
from .models import Producto

# Create your views here.

# /Productos


def index(request):
    productos = Producto.objects.select_related('categoria').all().values()
    return render(
        request,
        'index.html',
        context={'productos': productos}
    )


def detalle(request, producto_id):
    # try:
    #     producto = Producto.objects.get(id=producto_id)
    #     return render(request, 'detalle.html', context={'producto': producto})
    # except Producto.DoesNotExist:
    #     raise Http404()  # <-- Error 404

    producto = get_object_or_404(Producto, id=producto_id)

    return render(request, 'detalle.html', context={'producto': producto})


def formulario(request):

    if request.method == 'POST':
        form = ProductoForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/productos')
    else:
        form = ProductoForm()
    return render(
        request,
        'producto_form.html',
        {'form': form}
    )

productos/templates/detalle.html
{% extends 'base.html' %}

{% block content %}
<div>
    <h6> {{ producto.nombre }}</h6>
    <p> {{ producto.categoria }} </p>
    <p> {{ producto.stock }} </p>
    <p> {{ producto.puntaje }}</p>
    <p> {{ producto.creado_en}}</p>
</div>
{% endblock %}

productos/templates/index.html
{% extends 'base.html' %}

{% block content %}
<h1 class="text-primary">Productos</h1>

<a href= {% url "productos:formulario" %}> Nuevo Producto </a>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Stock</th>
            <th>Calificación</th>
        </tr>
    </thead>
    <tbody>
        {% for producto in productos %}
        <tr>
            <td> <a href="{% url 'productos:detalle' producto.id %}"> {{ producto.nombre }} </a></td>
            <td>{{ producto.stock }}</td>
            <td>{{ producto.puntaje }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

productos/templates/producto_form.html
{% extends 'base.html' %}

{% block content %}

<form 
    novalidate
    action= "{% url 'productos:formulario' %}"
    method='post'>
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Enviar"/>
</form>

{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Productos</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>

    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Alan Medina </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url "inicio" %}">Inicio</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href=" {% url 'productos:index' %} ">Productos</a>
              </li>
              
            </ul>
            <span class="navbar-text">
             
            </span>
          </div>
        </div>
      </nav>
    

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>

</html>

templates/django/forms/label.html
{% if use_tag %}<{{ tag }}{% include 'django/forms/attrs.html' %} class="form-label">{{ label }}</{{ tag }}>{% else %}{{ label }}{% endif %}

templates/django/forms/widgets/input.html
<input
class="form-control" 
type="{{ widget.type }}" 
name="{{ widget.name }}"
{% if widget.value != None %} 
    value="{{ widget.value|stringformat:'s' }}"
{% endif %}
{% include "django/forms/widgets/attrs.html" %}
>
</input>

templates/django/forms/widgets/select.html
<select class="form-select" name="{{ widget.name }}"{% include "django/forms/widgets/attrs.html" %}>{% for group_name, group_choices, group_index in widget.optgroups %}{% if group_name %}
    <optgroup label="{{ group_name }}">{% endif %}{% for option in group_choices %}
    {% include option.template_name with widget=option %}{% endfor %}{% if group_name %}
    </optgroup>{% endif %}{% endfor %}
</select>

templates/form_snippet.html
{% for field in form %}
    <div class="mb-3">
        {{ field.label_tag }}
        {% if field.errors %}
            {{ field }}
        {% else %}
            {{ field }}
        {% endif %}
        <div class="invalid-feedback">
            {% for error in field.errors %}
                {{ error }}
            {% endfor %}
        </div>
    </div>
{% endfor %}

templates/inicio.html
{% extends "base.html" %}

{% block content  %}
     Hola ! Bienvenidos a Productly

     Este es el inicio de mi pag

     Productly v1.1
{% endblock  content%}